### PR TITLE
Fix cfp button line height on mobile.

### PR DESCRIPTION
**Pull request by DevinClark**
HT to https://twitter.com/msanford/status/593443172455489536 for finding this.

### CODE REVIEW

**Comment by amandaharlin** [comment]
awesome! thanks for fixing it way before we launched!

**Comment by michaelsanford** [comment]
@DevinClark thanks for the shout-out! I hadn't realized the site was itself a public repo.

**Comment by amandaharlin** [comment]
@michaelsanford thank you for finding it. every bit of community support helps! we need folks like y'all to make our community work :+1: :dancer:

**Comment by amandaharlin** [comment]
we on fiah! :fire: ty for getting 2015 going @vlucas @the-simian

**Comment by the-simian** [comment]
ugh I knew about this and forgot to commit

**Comment by the-simian** [comment]
@DevinClark thanks!

**Pull request merged**
